<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/*.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../DiscordChatExporter.Gui/DiscordChatExporter.Gui.csproj" />
  </ItemGroup>
</Project>
